### ISSUE TITLE
cordova-plugin-camera requires a newer version of cordova-android

### ISSUE THREAD

**Issue by itaibs** [meteor/mobile-packages#110]
Hi. Hope this is the right place to ask this:

I followed the instructions for the mdg:camera package and on chrome everything works fine.
I'm trying to get this to work on android as well. When I start the app on android:

> meteor run android-device --mobile-server https://my-app-name.meteor.com

I get the following message:

> % Plugin doesn't support this project's cordova-android version. cordova-android: 4.1.1, failed version requirement: >=5.0.0-dev
% Skipping 'cordova-plugin-camera' for android

I'm guessing this is an easy-to-solve issue as I really didn't try anything fancy. Any help would be greatly appreciated :)

**Comment by martijnwalraven** [comment]
Upgrading to the latest Meteor 1.3 beta should fix this, because it includes `cordova-android` 5.1.0: https://github.com/meteor/meteor/issues/6266.

I don't think it should have tried to install this version of the `mdg:camera` package on Meteor 1.2, but that may have to do with [this commit](https://github.com/meteor/mobile-packages/commit/200e252b4bc487006b43bf4fbe1bb2aae13a38e8).

**Comment by itaibs** [comment]
Thanks for the quick reply!
I'm going to try and move to the beta version - but isn't there a way to fix this while still using a stable version?

**Comment by martijnwalraven** [comment]
You may be able to downgrade the camera package with `meteor update mdg:camera@1.2.0`.

**Comment by itaibs** [comment]
Updating this way doesn't work:

> $ meteor update mdg:camera@1.2.0
> => Errors while upgrading packages:           
>                                               
> While selecting package versions:
> error: Package names can only contain lowercase ASCII alphanumerics, dash, dot, or colon, not "@".

I tried removing and adding the package with the 1.2.0 version but this also didn't work:

> $ meteor remove mdg:camera
>                                               
> Changes to your project's package version selections:
>                                               
> mdg:camera  removed from your project         
> 
> mdg:camera removed dependency                

> $ meteor add mdg:camera@1.2.0
>                                               
> Changes to your project's package version selections:
>                                               
> mdg:camera  added, version 1.3.1              
> 

Any idea?

**Comment by martijnwalraven** [comment]
Oh, I'm sorry, this is confusing, but `meteor add mdg:camera@=1.2.0` should work (note the equals sign). See [here](http://docs.meteor.com/#/full/meteoradd) for why this is needed.

**Comment by itaibs** [comment]
OK. thanks for the help. Here are some followup issues (not sure if they should be opened in their own issues or on a different thread):

I decided to try the new beta release like you suggested in the beginning. This "solved" the camera issue (at least I don't see the warnings anymore), but it messed up my app on android in a different way. Now I can't sign in using facebook login (only on android, on chrome it works). I'm getting stuck on the facebook login page after entering username and password with a js exception: 

> Uncaught SyntaxError: Unexpected token _

So I'm trying to go back to the stable (1.2.1) meteor version:

> $ meteor update --release 1.2.1 

And this doesn't work due to weir dependency issues (long dump from my shell follows, apologies):

> Update to release METEOR@1.2.1 is impossible: 
> While selecting package versions:             
> error: Conflict: Constraint meteor@1.1.11-beta.11 is not satisfied by meteor 1.1.10.
> Constraints on package "meteor":
> * meteor@=1.1.10 <- top level
> * meteor@1.1.7 <- meteor-base 1.0.1
> * meteor@1.1.7 <- underscore 1.0.4
> * meteor@1.1.10 <- webapp 1.2.3 <- accounts-oauth 1.1.8 <- accounts-facebook 1.0.6
> * meteor@1.1.10 <- webapp 1.2.3 <- meteor-base 1.0.1
> * meteor@1.1.7 <- logging 1.0.8 <- oauth 1.1.6 <- accounts-oauth 1.1.8 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- logging 1.0.8 <- webapp 1.2.3 <- meteor-base 1.0.1
> * meteor@1.1.7 <- ejson 1.0.7 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- ejson 1.0.7 <- check 1.1.0
> * meteor@1.1.7 <- base64 1.0.4 <- ejson 1.0.7 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- base64 1.0.4 <- ejson 1.0.7 <- check 1.1.0
> * meteor@1.1.7 <- routepolicy 1.0.6 <- ddp-server 1.2.2 <- ddp 1.2.2 <- accounts-base 1.2.2 <-
> accounts-facebook 1.0.6
> * meteor@1.1.7 <- routepolicy 1.0.6 <- ddp-server 1.2.2 <- ddp 1.2.2 <- mdg:validated-method 1.0.1
> * meteor@1.1.7 <- routepolicy 1.0.6 <- webapp 1.2.3 <- meteor-base 1.0.1
> * meteor@1.1.7 <- boilerplate-generator 1.0.4 <- webapp 1.2.3 <- accounts-oauth 1.1.8 <-
> accounts-facebook 1.0.6
> * meteor@1.1.7 <- boilerplate-generator 1.0.4 <- webapp 1.2.3 <- meteor-base 1.0.1
> * meteor@1.1.7 <- spacebars-compiler 1.0.7 <- boilerplate-generator 1.0.4 <- webapp 1.2.3 <-
> accounts-oauth 1.1.8 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- spacebars-compiler 1.0.7 <- boilerplate-generator 1.0.4 <- webapp 1.2.3 <-
> meteor-base 1.0.1
> * meteor@1.1.7 <- htmljs 1.0.5 <- blaze 2.1.3 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- htmljs 1.0.5 <- blaze 2.1.3 <- alanning:roles 1.2.14
> * meteor@1.1.7 <- deps 1.0.9 <- aldeed:simple-schema 1.5.3 <- aldeed:collection2-core 1.0.0 <-
> aldeed:collection2 2.8.0
> * meteor@1.1.9 <- tracker 1.0.9
> * meteor@1.1.7 <- html-tools 1.0.5 <- angular-templates 0.0.3 <- angular 1.3.6
> * meteor@1.1.7 <- blaze-tools 1.0.4 <- spacebars-compiler 1.0.7 <- boilerplate-generator 1.0.4 <-
> webapp 1.2.3 <- accounts-oauth 1.1.8 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- blaze-tools 1.0.4 <- spacebars-compiler 1.0.7 <- boilerplate-generator 1.0.4 <-
> webapp 1.2.3 <- meteor-base 1.0.1
> * meteor@1.1.7 <- spacebars 1.0.7 <- blaze-html-templates 1.0.1 <- dotansimha:accounts-ui-angular
> 0.0.2
> * meteor@1.1.7 <- blaze 2.1.3 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- blaze 2.1.3 <- alanning:roles 1.2.14
> * meteor@1.1.7 <- jquery 1.11.4
> * meteor@1.1.10 <- check 1.1.0
> * meteor@1.1.7 <- observe-sequence 1.0.7 <- angular-meteor-data 0.2.0 <- angular 1.3.6
> * meteor@1.1.7 <- mongo-id 1.0.1 <- angular-meteor-data 0.2.0 <- angular 1.3.6
> * meteor@1.1.7 <- mongo-id 1.0.1 <- mongo 1.1.3
> * meteor@1.1.7 <- id-map 1.0.4 <- binary-heap 1.0.4 <- mongo 1.1.3
> * meteor@1.1.10 <- random 1.0.5 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.10 <- random 1.0.5 <- mongo 1.1.3
> * meteor@1.1.10 <- ecmascript 0.1.6 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.10 <- ecmascript 0.1.6 <- mdg:validated-method 1.0.1
> * meteor@1.1.7 <- babel-compiler 5.8.24_1 <- ecmascript 0.1.6 <- accounts-base 1.2.2 <-
> accounts-facebook 1.0.6
> * meteor@1.1.7 <- babel-compiler 5.8.24_1 <- ecmascript 0.1.6 <- mdg:validated-method 1.0.1
> * meteor@1.1.7 <- babel-runtime 0.1.4 <- ecmascript 0.1.6 <- accounts-base 1.2.2 <- accounts-facebook
> 1.0.6
> * meteor@1.1.7 <- babel-runtime 0.1.4 <- ecmascript 0.1.6 <- mdg:validated-method 1.0.1
> * meteor@1.1.10 <- ecmascript-runtime 0.2.6 <- ecmascript 0.1.6 <- accounts-base 1.2.2 <-
> accounts-facebook 1.0.6
> * meteor@1.1.10 <- ecmascript-runtime 0.2.6 <- ecmascript 0.1.6 <- mdg:validated-method 1.0.1
> * meteor@1.1.10 <- promise 0.5.1 <- ecmascript 0.1.6 <- accounts-base 1.2.2 <- accounts-facebook
> 1.0.6
> * meteor@1.1.10 <- promise 0.5.1 <- ecmascript 0.1.6 <- mdg:validated-method 1.0.1
> * meteor@1.1.7 <- diff-sequence 1.0.1 <- angular-meteor-data 0.2.0 <- angular 1.3.6
> * meteor@1.1.7 <- diff-sequence 1.0.1 <- mongo 1.1.3
> * meteor@1.1.7 <- reactive-var 1.0.6
> * meteor@1.1.7 <- ui 1.0.8 <- blaze-html-templates 1.0.1 <- dotansimha:accounts-ui-angular 0.0.2
> * meteor@1.1.7 <- webapp-hashing 1.0.5 <- webapp 1.2.3 <- accounts-oauth 1.1.8 <- accounts-facebook
> 1.0.6
> * meteor@1.1.7 <- webapp-hashing 1.0.5 <- webapp 1.2.3 <- meteor-base 1.0.1
> * meteor@1.1.7 <- ddp 1.2.2 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- ddp 1.2.2 <- mdg:validated-method 1.0.1
> * meteor@1.1.7 <- ddp-client 1.2.1 <- ddp 1.2.2 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- ddp-client 1.2.1 <- ddp 1.2.2 <- mdg:validated-method 1.0.1
> * meteor@1.1.7 <- retry 1.0.4 <- autoupdate 1.2.4 <- hot-code-push 1.0.0 <- meteor-base 1.0.1
> * meteor@1.1.10 <- ddp-common 1.2.2 <- ddp-client 1.2.1 <- ddp 1.2.2 <- accounts-base 1.2.2 <-
> accounts-facebook 1.0.6
> * meteor@1.1.10 <- ddp-common 1.2.2 <- ddp-client 1.2.1 <- ddp 1.2.2 <- mdg:validated-method 1.0.1
> * meteor@1.1.10 <- ddp-server 1.2.2 <- ddp 1.2.2 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.10 <- ddp-server 1.2.2 <- ddp 1.2.2 <- mdg:validated-method 1.0.1
> * meteor@1.1.7 <- callback-hook 1.0.4 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- callback-hook 1.0.4 <- mongo 1.1.3
> * meteor@1.1.9 <- minimongo 1.0.10 <- aldeed:collection2-core 1.0.0 <- aldeed:collection2 2.8.0
> * meteor@1.1.9 <- minimongo 1.0.10 <- matb33:collection-hooks 0.8.1
> * meteor@1.1.7 <- ordered-dict 1.0.4 <- minimongo 1.0.10 <- aldeed:collection2-core 1.0.0 <-
> aldeed:collection2 2.8.0
> * meteor@1.1.7 <- ordered-dict 1.0.4 <- minimongo 1.0.10 <- matb33:collection-hooks 0.8.1
> * meteor@1.1.7 <- geojson-utils 1.0.4 <- minimongo 1.0.10 <- aldeed:collection2-core 1.0.0 <-
> aldeed:collection2 2.8.0
> * meteor@1.1.7 <- geojson-utils 1.0.4 <- minimongo 1.0.10 <- matb33:collection-hooks 0.8.1
> * meteor@1.1.7 <- livedata 1.0.15 <- meteor-base 1.0.1
> * meteor@1.1.7 <- hot-code-push 1.0.0 <- meteor-base 1.0.1
> * meteor@1.1.10 <- autoupdate 1.2.4 <- hot-code-push 1.0.0 <- meteor-base 1.0.1
> * meteor@1.1.10 <- mongo 1.1.3
> * meteor@1.1.7 <- npm-mongo 1.4.39_1 <- mongo 1.1.3
> * meteor@1.1.7 <- binary-heap 1.0.4 <- mongo 1.1.3
> * meteor@1.1.7 <- http 1.1.1 <- autoupdate 1.2.4 <- hot-code-push 1.0.0 <- meteor-base 1.0.1
> * meteor@1.1.7 <- http 1.1.1 <- facebook 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- url 1.0.5 <- http 1.1.1 <- autoupdate 1.2.4 <- hot-code-push 1.0.0 <- meteor-base
> 1.0.1
> * meteor@1.1.7 <- url 1.0.5 <- http 1.1.1 <- facebook 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- reload 1.1.4 <- ddp-client 1.2.1 <- ddp 1.2.2 <- accounts-base 1.2.2 <-
> accounts-facebook 1.0.6
> * meteor@1.1.7 <- reload 1.1.4 <- ddp-client 1.2.1 <- ddp 1.2.2 <- mdg:validated-method 1.0.1
> * meteor@1.1.7 <- reload 1.1.4 <- hot-code-push 1.0.0 <- meteor-base 1.0.1
> * meteor@1.1.7 <- reload 1.1.4 <- mdg:reload-on-resume 1.0.4
> * meteor@1.1.7 <- mobile-experience 1.0.1
> * meteor@1.1.7 <- launch-screen 1.0.4 <- mobile-experience 1.0.1
> * meteor@1.1.7 <- fastclick 1.0.7 <- mobile-experience 1.0.1
> * meteor@1.1.7 <- mobile-status-bar 1.0.6 <- mobile-experience 1.0.1
> * meteor@1.1.7 <- session 1.1.1
> * meteor@1.1.10 <- reactive-dict 1.1.3 <- session 1.1.1
> * meteor@1.1.10 <- es5-shim 4.1.14
> * meteor@1.1.9 <- caching-html-compiler 1.0.2 <- angular-templates 0.0.3 <- angular 1.3.6
> * meteor@1.1.7 <- caching-compiler 1.0.0 <- caching-html-compiler 1.0.2 <- angular-templates 0.0.3 <-
> angular 1.3.6
> * meteor@1.1.7 <- templating-tools 1.0.0 <- angular-templates 0.0.3 <- angular 1.3.6
> * meteor@1.1.7 <- minifiers 1.1.7 <- spacebars-compiler 1.0.7 <- boilerplate-generator 1.0.4 <-
> webapp 1.2.3 <- accounts-oauth 1.1.8 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- minifiers 1.1.7 <- spacebars-compiler 1.0.7 <- boilerplate-generator 1.0.4 <-
> webapp 1.2.3 <- meteor-base 1.0.1
> * meteor@1.1.7 <- minifiers 1.1.7 <- templating-tools 1.0.0 <- angular-templates 0.0.3 <- angular
> 1.3.6
> * meteor@1.1.7 <- accounts-facebook 1.0.6
> * meteor@1.1.10 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- ddp-rate-limiter 1.0.0 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- rate-limit 1.0.0 <- ddp-rate-limiter 1.0.0 <- accounts-base 1.2.2 <-
> accounts-facebook 1.0.6
> * meteor@1.1.7 <- service-configuration 1.0.5 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- localstorage 1.0.5 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.10 <- accounts-oauth 1.1.8 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- oauth 1.1.6 <- accounts-oauth 1.1.8 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- facebook 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.7 <- oauth2 1.1.5 <- facebook 1.2.2 <- accounts-facebook 1.0.6
> * meteor@1.1.10 <- templating 1.1.5 <- accounts-ui-unstyled 1.1.8 <- accounts-ui 1.1.6 <-
> dotansimha:accounts-ui-angular 0.0.2
> * meteor@1.1.10 <- templating 1.1.5 <- blaze-html-templates 1.0.1 <- dotansimha:accounts-ui-angular
> 0.0.2
> * meteor@1.1.10 <- templating 1.1.5 <- tmeasday:publish-counts 0.7.3
> * meteor@1.1.7 <- accounts-ui 1.1.6 <- dotansimha:accounts-ui-angular 0.0.2
> * meteor@1.1.7 <- accounts-ui-unstyled 1.1.8 <- accounts-ui 1.1.6 <- dotansimha:accounts-ui-angular
> 0.0.2
> * meteor@1.1.10 <- less 2.5.1 <- accounts-ui 1.1.6 <- dotansimha:accounts-ui-angular 0.0.2
> * meteor@1.1.7 <- blaze-html-templates 1.0.1 <- dotansimha:accounts-ui-angular 0.0.2
> * meteor@1.1.9 <- crosswalk 1.3.1
> * meteor@1.1.11-beta.11 <- standard-minifier-css 1.0.3-beta.11
> * meteor@1.1.11-beta.11 <- minifier-css 1.1.8-beta.11 <- standard-minifier-css 1.0.3-beta.11
> * meteor@1.1.11-beta.11 <- standard-minifier-js 1.0.3-beta.11
> * meteor@1.1.11-beta.11 <- minifier-js 1.1.8-beta.11 <- standard-minifier-js 1.0.3-beta.11
> 
> Conflict: Constraint underscore@1.0.5-beta.11 is not satisfied by underscore 1.0.4.
> Constraints on package "underscore":
> * underscore@=1.0.4 <- top level
> * underscore@1.0.4 <- meteor-base 1.0.1
> * underscore@1.0.4 <- meteor 1.1.10 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- meteor 1.1.10 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- webapp 1.2.3 <- accounts-oauth 1.1.8 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- webapp 1.2.3 <- meteor-base 1.0.1
> * underscore@1.0.4 <- logging 1.0.8 <- oauth 1.1.6 <- accounts-oauth 1.1.8 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- logging 1.0.8 <- webapp 1.2.3 <- meteor-base 1.0.1
> * underscore@1.0.4 <- ejson 1.0.7 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- ejson 1.0.7 <- check 1.1.0
> * underscore@1.0.4 <- routepolicy 1.0.6 <- ddp-server 1.2.2 <- ddp 1.2.2 <- accounts-base 1.2.2 <-
> accounts-facebook 1.0.6
> * underscore@1.0.4 <- routepolicy 1.0.6 <- ddp-server 1.2.2 <- ddp 1.2.2 <- mdg:validated-method
> 1.0.1
> * underscore@1.0.4 <- routepolicy 1.0.6 <- webapp 1.2.3 <- meteor-base 1.0.1
> * underscore@1.0.4 <- boilerplate-generator 1.0.4 <- webapp 1.2.3 <- accounts-oauth 1.1.8 <-
> accounts-facebook 1.0.6
> * underscore@1.0.4 <- boilerplate-generator 1.0.4 <- webapp 1.2.3 <- meteor-base 1.0.1
> * underscore@1.0.4 <- spacebars-compiler 1.0.7 <- boilerplate-generator 1.0.4 <- webapp 1.2.3 <-
> accounts-oauth 1.1.8 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- spacebars-compiler 1.0.7 <- boilerplate-generator 1.0.4 <- webapp 1.2.3 <-
> meteor-base 1.0.1
> * underscore@1.0.4 <- blaze-tools 1.0.4 <- spacebars-compiler 1.0.7 <- boilerplate-generator 1.0.4 <-
> webapp 1.2.3 <- accounts-oauth 1.1.8 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- blaze-tools 1.0.4 <- spacebars-compiler 1.0.7 <- boilerplate-generator 1.0.4 <-
> webapp 1.2.3 <- meteor-base 1.0.1
> * underscore@1.0.4 <- spacebars 1.0.7 <- blaze-html-templates 1.0.1 <- dotansimha:accounts-ui-angular
> 0.0.2
> * underscore@1.0.4 <- blaze 2.1.3 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- blaze 2.1.3 <- alanning:roles 1.2.14
> * underscore@1.0.4 <- check 1.1.0
> * underscore@1.0.4 <- observe-sequence 1.0.7 <- angular-meteor-data 0.2.0 <- angular 1.3.6
> * underscore@1.0.4 <- id-map 1.0.4 <- binary-heap 1.0.4 <- mongo 1.1.3
> * underscore@1.0.4 <- random 1.0.5 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- random 1.0.5 <- mongo 1.1.3
> * underscore@1.0.4 <- diff-sequence 1.0.1 <- angular-meteor-data 0.2.0 <- angular 1.3.6
> * underscore@1.0.4 <- diff-sequence 1.0.1 <- mongo 1.1.3
> * underscore@1.0.4 <- webapp-hashing 1.0.5 <- webapp 1.2.3 <- accounts-oauth 1.1.8 <-
> accounts-facebook 1.0.6
> * underscore@1.0.4 <- webapp-hashing 1.0.5 <- webapp 1.2.3 <- meteor-base 1.0.1
> * underscore@1.0.4 <- ddp-client 1.2.1 <- ddp 1.2.2 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- ddp-client 1.2.1 <- ddp 1.2.2 <- mdg:validated-method 1.0.1
> * underscore@1.0.4 <- retry 1.0.4 <- autoupdate 1.2.4 <- hot-code-push 1.0.0 <- meteor-base 1.0.1
> * underscore@1.0.4 <- ddp-common 1.2.2 <- ddp-client 1.2.1 <- ddp 1.2.2 <- accounts-base 1.2.2 <-
> accounts-facebook 1.0.6
> * underscore@1.0.4 <- ddp-common 1.2.2 <- ddp-client 1.2.1 <- ddp 1.2.2 <- mdg:validated-method 1.0.1
> * underscore@1.0.4 <- ddp-server 1.2.2 <- ddp 1.2.2 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- ddp-server 1.2.2 <- ddp 1.2.2 <- mdg:validated-method 1.0.1
> * underscore@1.0.4 <- callback-hook 1.0.4 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- callback-hook 1.0.4 <- mongo 1.1.3
> * underscore@1.0.4 <- minimongo 1.0.10 <- aldeed:collection2-core 1.0.0 <- aldeed:collection2 2.8.0
> * underscore@1.0.4 <- minimongo 1.0.10 <- matb33:collection-hooks 0.8.1
> * underscore@1.0.4 <- ordered-dict 1.0.4 <- minimongo 1.0.10 <- aldeed:collection2-core 1.0.0 <-
> aldeed:collection2 2.8.0
> * underscore@1.0.4 <- ordered-dict 1.0.4 <- minimongo 1.0.10 <- matb33:collection-hooks 0.8.1
> * underscore@1.0.4 <- autoupdate 1.2.4 <- hot-code-push 1.0.0 <- meteor-base 1.0.1
> * underscore@1.0.4 <- mongo 1.1.3
> * underscore@1.0.4 <- binary-heap 1.0.4 <- mongo 1.1.3
> * underscore@1.0.4 <- http 1.1.1 <- autoupdate 1.2.4 <- hot-code-push 1.0.0 <- meteor-base 1.0.1
> * underscore@1.0.4 <- http 1.1.1 <- facebook 1.2.2 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- url 1.0.5 <- http 1.1.1 <- autoupdate 1.2.4 <- hot-code-push 1.0.0 <-
> meteor-base 1.0.1
> * underscore@1.0.4 <- url 1.0.5 <- http 1.1.1 <- facebook 1.2.2 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- reload 1.1.4 <- ddp-client 1.2.1 <- ddp 1.2.2 <- accounts-base 1.2.2 <-
> accounts-facebook 1.0.6
> * underscore@1.0.4 <- reload 1.1.4 <- ddp-client 1.2.1 <- ddp 1.2.2 <- mdg:validated-method 1.0.1
> * underscore@1.0.4 <- reload 1.1.4 <- hot-code-push 1.0.0 <- meteor-base 1.0.1
> * underscore@1.0.4 <- reload 1.1.4 <- mdg:reload-on-resume 1.0.4
> * underscore@1.0.4 <- session 1.1.1
> * underscore@1.0.4 <- reactive-dict 1.1.3 <- session 1.1.1
> * underscore@1.0.1 <- dburles:mongo-collection-instances 0.3.4 <- angular-meteor-data 0.2.0 <-
> angular 1.3.6
> * underscore@1.0.4 <- caching-html-compiler 1.0.2 <- angular-templates 0.0.3 <- angular 1.3.6
> * underscore@1.0.4 <- templating-tools 1.0.0 <- angular-templates 0.0.3 <- angular 1.3.6
> * underscore@1.0.4 <- minifiers 1.1.7 <- spacebars-compiler 1.0.7 <- boilerplate-generator 1.0.4 <-
> webapp 1.2.3 <- accounts-oauth 1.1.8 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- minifiers 1.1.7 <- spacebars-compiler 1.0.7 <- boilerplate-generator 1.0.4 <-
> webapp 1.2.3 <- meteor-base 1.0.1
> * underscore@1.0.4 <- minifiers 1.1.7 <- templating-tools 1.0.0 <- angular-templates 0.0.3 <- angular
> 1.3.6
> * underscore@1.0.4 <- angular-meteor-data 0.2.0 <- angular 1.3.6
> * underscore@1.0.4 <- angular-templates 0.0.3 <- angular 1.3.6
> * underscore@1.0.4 <- accounts-base 1.2.2 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- rate-limit 1.0.0 <- ddp-rate-limiter 1.0.0 <- accounts-base 1.2.2 <-
> accounts-facebook 1.0.6
> * underscore@1.0.4 <- accounts-oauth 1.1.8 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- oauth 1.1.6 <- accounts-oauth 1.1.8 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- facebook 1.2.2 <- accounts-facebook 1.0.6
> * underscore@1.0.4 <- templating 1.1.5 <- accounts-ui-unstyled 1.1.8 <- accounts-ui 1.1.6 <-
> dotansimha:accounts-ui-angular 0.0.2
> * underscore@1.0.4 <- templating 1.1.5 <- blaze-html-templates 1.0.1 <-
> dotansimha:accounts-ui-angular 0.0.2
> * underscore@1.0.4 <- templating 1.1.5 <- tmeasday:publish-counts 0.7.3
> * underscore@1.0.4 <- accounts-ui-unstyled 1.1.8 <- accounts-ui 1.1.6 <-
> dotansimha:accounts-ui-angular 0.0.2
> * underscore@1.0.4 <- less 2.5.1 <- accounts-ui 1.1.6 <- dotansimha:accounts-ui-angular 0.0.2
> * underscore@1.0.4 <- alanning:roles 1.2.14
> * underscore@1.0.2 <- thinksoftware:image-resize-client 1.0.0
> * underscore@1.0.0 <- aldeed:simple-schema 1.5.3 <- aldeed:collection2-core 1.0.0 <-
> aldeed:collection2 2.8.0
> * underscore@1.0.1 <- raix:eventemitter 0.1.3 <- aldeed:collection2-core 1.0.0 <- aldeed:collection2
> 2.8.0
> * underscore@1.0.0 <- aldeed:collection2-core 1.0.0 <- aldeed:collection2 2.8.0
> * underscore@1.0.0 <- aldeed:schema-index 1.0.1 <- aldeed:collection2 2.8.0
> * underscore@1.0.0 <- aldeed:schema-deny 1.0.1 <- aldeed:collection2 2.8.0
> * underscore@1.0.4 <- mdg:validated-method 1.0.1
> * underscore@1.0.3 <- matb33:collection-hooks 0.8.1
> * underscore@1.0.5-beta.11 <- minifier-css 1.1.8-beta.11 <- standard-minifier-css 1.0.3-beta.11
> * underscore@1.0.5-beta.11 <- minifier-js 1.1.8-beta.11 <- standard-minifier-js 1.0.3-beta.11
> 
> This project is at the latest release which is compatible with your current package constraints.

Kind of in a loss here. No idea how to continue from here :/.

**Comment by martijnwalraven** [comment]
Could you open a separate issue on the `meteor/meteor` repo for the Facebook login issue? This seems worth investigating further, and having a separate issue makes it easier to keep track of these things.

Downgrading to an earlier release of Meteor is usually not possible. The best way is to revert to an earlier version of your project in Git or other version control.

**Comment by itaibs** [comment]
Thanks. I'll revert to an older version in my git repository and report back.

FYI: I was able to downgrade to @1.2.1 after removing the standard-minifier-js/css packages. But I'm guessing this isn't a good practice :)

**Comment by itaibs** [comment]
To close the loop on this issue:
I managed to g back to an older version of my code with the stable version. I then added the mdg:camera package at 1.2.0. It works now on android as expected :). Now, however, there's an error when using it on chrome:
Uncaught TypeError: stream.stop is not a function

And the camera stays on. The rest of the flow works ok.

I'm not going to investigate that further since desktop isn't important for my project, but just an fyi :).

Thanks a lot for all the help!!

**Comment by robinnewhouse** [comment]
I'm having this same issue. Shouldn't the current version of this package should be compatible with the current stable version of meteor?

**Comment by martijnwalraven** [comment]
The issue here is that plugin versions sometimes only work with certain Cordova versions. So the `isobuild:cordova` constraint is there to ensure we don't try to install a newer version of the plugin in a Meteor project with an older version of Cordova. That is what went wrong here, so then you get a compile time or run time error.

In this case, a new version of `cordova-plugin-camera` has restored compatibility with an earlier `cordova-android` version. So I've published a new version of this package which restores compatibility with Meteor 1.2.
