### ISSUE TITLE
Not compatible with Meteor 1.3

### ISSUE THREAD

**Issue by aalhaimi** [meteor/mobile-packages#115]
Simple-photo example doesn't work properly with Meteor 1.3. Please update accordingly.

**Comment by robertross** [comment]
+!

Has anyone got this working in production with 1.3? I'm doing my best but no joy as yet. Camera silll fails on mobile browsers.

**Comment by aalhaimi** [comment]
@robertross I went with this [Meteor-Uploads ](https://github.com/tomitrescak/meteor-uploads) for the time being. It works well on desktop and mobile.. Allows users to choose from image gallery on mobile. check it out.

**Comment by krishaamer** [comment]
Any update on this?
