### ISSUE TITLE
Meteor 1.3 gives 'Blaze.render without parent is deprecated'

### ISSUE THREAD

**Issue by ghost** [meteor/mobile-packages#117]
Hi
I'm getting these messages when calling .getPicture (please see screenShot)
They originate in the Blaze.render method (see screenShot).
I can't find out how to prevent this?
Any suggestions are more than welcome!
Thanks
Mark

<img width="1301" alt="screen shot 2016-05-11 at 00 06 46" src="https://cloud.githubusercontent.com/assets/3906493/15149318/5fa1a922-170c-11e6-8e9c-811750373b20.png">

<img width="294" alt="screen shot 2016-05-11 at 00 10 08" src="https://cloud.githubusercontent.com/assets/3906493/15149444/ea44968e-170c-11e6-81ec-b24bb4b6f188.png">

**Comment by nubestra** [comment]
Im having same problem in meteor 1.4.2

**Comment by StorytellerCZ** [comment]
Maybe related to #153 ?
