### ISSUE TITLE
no plugin found for camera.less in mdg:camera

### ISSUE THREAD

**Issue by hamedhemmati** [meteor/mobile-packages#123]
I think the less included with this package is too old to work with meteor 1.4. Can you verify if this is the issue and if so update the package dependency?

**Comment by Ajaay** [comment]
I'm getting the same issue on 1.4

**Comment by DaFrik** [comment]
got the same problem too :( 

tried 

`meteor add less`

but didnt work

**Comment by ajschmaltz** [comment]
What did you guys do to work around this on 1.4?

**Comment by jcharvet** [comment]
I have the same issue

**Comment by hazio** [comment]
I have the same issue too..
"error: no plugin found for camera.less in mdg:camera; a plugin for *.less was active when it was published but none is now"

I tried to downgrade the mdg:camera package version to 1.2.0, but that didn't help.

**Comment by obarrera99** [comment]
Hi Everybody... You can use this version 

meteor create projectname --release 1.3.4.1
meteor add mdg:camera
meteor

After that
***********************    main.html  ********
<head>
  <title>camera</title>
</head>
<body>
  <h1>smile!</h1>
  {{> example}}
</body>

<template name="example">
    <a href="#" class="takePhoto">Capturar Imagen</a>
    <img class="photo">
</template>


**************************************  main.js
Template.example.events({
    'click .takePhoto': function(event, template) {
        var cameraOptions = {
            width: 800,
            height: 600
        };
        MeteorCamera.getPicture(cameraOptions, function (error, data) {
           if (!error) {
               template.$('.photo').attr('src', data);
           }
        });
        event.preventDefault();
    }
});

**Comment by mattiLeBlanc** [comment]
@obarrera99 Why would I downgrade my Meteor 1.4?? 
That is not a fix.

**Comment by csellis** [comment]
Has anyone found a solution yet?

**Comment by KaroseLiu** [comment]
I have the same issue on Meteor 1.4, so any suggestions?

**Comment by joaosalless** [comment]
I have the same issue on Meteor 1.4.2

```
=> Errors prevented startup:                  
   
   While building for web.browser:
   error: no plugin found for camera.less in mdg:camera; a plugin for *.less was active when it was published
   but none is now
   
=> Your application has errors. Waiting for file change.

```
Anyone have any suggestions that can solve this problem?

**Comment by nialexsan** [comment]
This plugin works without errors if you use it as local package. 
For this:

1. copy `mdg:camera`  into `package` folder of your project 

2. change name of the package in the `package.js` file from `mdg:camera` to `camera`

3. add `camera` to `package` file in `.meteor` folder

**Comment by SanjeethKumarTS** [comment]
meteor create projectname --release 1.3.4.1
meteor add mdg:camera
meteor

and **meteor update** after
This worked for me

**Comment by NicholasEli** [comment]
Bump, just ran into this issue on the latest version of Meteor.

**Comment by willbeh** [comment]
Had the same issue with Meteor 1.4.3
I tried to add these first
meteor add less
meteor add session

then only
meteor add mdg:camera

Seems to work.

**Comment by Mutai-Kenn** [comment]
Yep i started with 
meteor add less  (which i get 2.7.8)
then install
meteor add mdg:camera
The version you get when you install mdg: camera at first before you independently install less gives (less version 1.0.14)
Reason i dont know but that approach works for me

**Comment by ShortyVee** [comment]
As @Mutai-Kenn  Stated, 
you just need to install a newer version of less.
put less@2.7.8 into your packages file.

**Comment by Axel4444** [comment]
First
meteor add mdg:camera

Later
meteor add mdg:chromatic

This worked for me

**Comment by wesleyfsmith** [comment]
```
meteor update less
```

That worked for me. I think this error is happening because some of these mdg packages aren't required their dependencies to update anymore now that they have been moved out of meteor core, but that's just a guess.

**Comment by suyuti** [comment]
`meteor remove mdg:camera
meteor remove less
meteor add less
meteor removemdg:camera`

Clean installation  worked for me.

Meteor version 1.4.2.3
less version 2.7.8
mdg:camera version 1.4.1
