### ISSUE TITLE
geolocation does not work with Meteor 1.4+

### ISSUE THREAD

**Issue by MichelFloyd** [meteor/mobile-packages#127]
Location is always returned as null.

**Comment by immigrantsheep** [comment]
can confirm for me as well

**Comment by jrsakizci** [comment]
Actually, it is working. But the problem is: when you enter site for the first time it returns null, but if you change route without reload the page, then its working. Strange error.

**Comment by jesperordrup** [comment]
@jrsakizci 
Same here.. calling a few times then it works

**Comment by StorytellerCZ** [comment]
Closing in favor of #133
