### ISSUE TITLE
geolocation is showing null.

### ISSUE THREAD

**Issue by varunajmera0** [meteor/mobile-packages#129]
it is not working. fix ur bug with METEOR@1.4.2.6.
Geolocation failed: Network location provider at 'https://www.googleapis.com/' : Returned error code 403.

**Comment by rashmimhatre100** [comment]
Still struggling with the same error. Any solution?

**Comment by StorytellerCZ** [comment]
If you are referencing to the map example you need to edit it and add in your API key.
Else see #133
