### ISSUE TITLE
Geolocation.currentLocation() not working, giving null value using meteor(1.5.1) & mdg:geolocation(1.3.0)

### ISSUE THREAD

**Issue by deligence** [meteor/mobile-packages#133]
Hello,

I am working in a meteor project(1.5.1) and using mdg:geolocation@1.3.0, and i am trying to get the value of Geolocation.currentLocation() but it is giving me null value and the behaviour is not the same for all the time, sometime it is giving me null value and sometime giving me proper value.

I have research for the long time, but not got the solution yet, if possible please provide solution with meteor@1.5.1 and with use of mdg:geolocation package.

Thanks in advance...

**Comment by rashmimhatre100** [comment]
Any breakthrough?? Same problem.

**Comment by theodorDiaconu** [comment]
I also had issues with this, I do not know what fixed it I am now experiencing issues with iOS cordova app, location is not being asked.

**Comment by jesperordrup** [comment]
I typically need to call latLng() or currentLocation() a couple of times before it returns a position. The first time(s) it returns null.

**Comment by laurent-kouassi** [comment]
Hey guys, I’m experiencing the same issues. Any help through?

**Comment by StorytellerCZ** [comment]
This might be related to not receiving permissions and/or potential lag between receiving the permissions and getting the data. I have tested it today and could only noticed a the two cases described. If anyone could provide a reliable reproduction that would be great.
