### ISSUE TITLE
Apple requires me to customize the notification prompt that asks the user for permission

### ISSUE THREAD

**Issue by janjackson** [meteor/mobile-packages#137]
I cannot upload my Meteor/Cordova app to the iOS store because suddenly they require me to specifically state what I need this feature for in the app. Is there a way to customize the popup with mdg:geolocation? If not, how else can I solve this? Shouldn't a lot of people have this issue?
Thanks in advance :)

**Comment by skirunman** [comment]
Yes, a lot of people have asked for same ability to customize the notification prompts:

https://github.com/meteor/mobile-packages/issues/68
https://github.com/meteor/mobile-packages/issues/88
https://github.com/meteor/mobile-packages/issues/100
https://forums.meteor.com/t/meteor-cordova-add-permissions/10625

It looks like the easiest way forward for you may be to use the [Cordova Diagnostic Plugin](https://github.com/dpa99c/cordova-diagnostic-plugin) to customize the notification prompts.

The other way to go is to create an "empty plugin" and set the values in that plugin's `plugin.xml` file, see [this as an example](https://github.com/DispatchMe/cordova-crosswalk-permissions). This is what we have done and our code looks something like:

```
<?xml version="1.0" encoding="utf-8"?>
<plugin xmlns="http://www.phonegap.com/ns/plugins/1.0" id="cordova-plugin-clozer" version="0.0.1">
  <name>Clozer App Configuration</name>
  <engines>
    <engine name="cordova" version=">=7.0.0"/>
  </engines>
  <platform name="ios">
    <config-file platform="ios" target="*-Info.plist" parent="NSCameraUsageDescription">
      <string>Please allow Clozer access to your phone's camera to capture images for upload.</string>
    </config-file>
  </platform>
</plugin>
```

Ideally how to do this should be added to the [Meteor Guide](https://guide.meteor.com/mobile.html) and it would be possible to specify these notification prompt strings in your app's `mobile-config.js` file something like:
```
  App.configurePlugin('cordova-plugin-camera', {
    NSCameraUsageDescription: 'Please allow Clozer access to your camera to capture images for upload.'
  });
```

Finally, how Cordova plugin's deal iOS usage descriptions is changing in their latest release of these plugins:

> cordova-plugin-camera, cordova-plugin-contacts, cordova-plugin-media, cordova-plugin-geolocation, and cordova-plugin-media-capture. Usage descriptions are required for iOS applications accessing certain apis. Apple wants to know why your app needs certain permissions. We now recommend you add the usage description to your app via edit-config tag. View the iOS Quirks section of the plugin documentation to see an example of how to use it.

https://cordova.apache.org/news/2017/11/10/plugins-release.html

Therefore it may be possible with these new plugins to set the notification string value in `mobile-config.js` using `edit-config` tag, but this needs testing.

@abernix Bring this to your attention as this will have some side effects on future Meteor Cordova versions.

**Comment by skirunman** [comment]
OK, I may have a solution for you. Try adding the following to your `mobile-config.js` and then rebuilding. Make sure you have removed your `.meteor/local/cordova-build/` directory between builds because of this https://github.com/meteor/meteor/issues/4234 just to be safe. 

```
App.appendToConfig(`
  <edit-config target="NSLocationWhenInUseUsageDescription" file="*-Info.plist" mode="merge">
    <string>My app needs access to your location for navigation purposes</string>
  </edit-config>
`);
```

Of course you can change the text string to whatever you want.

**Comment by skirunman** [comment]
@janjackson Did you try this? Others have [confirmed it works](https://forums.meteor.com/t/ios-geolocation-message/41150).
