### ISSUE TITLE
On cordova mdg:geolocation doesn't wait for the cordova-geolocation-plugin to be ready

### ISSUE THREAD

**Issue by cwohlman** [meteor/mobile-packages#139]
I'm running into an issue on ios where the mdg:geolocation package doesn't wait for the cordova plugin to be ready, so in cases where navigator.geolocation is available but not functioning (ios 11) the package incorrectly uses navigator.geolocation but fails to actually acquire any location information. Later the cordova plugin loads but the package doesn't attempt to re-initialize any watch.

**Comment by StorytellerCZ** [comment]
I'm closing this issue due to age.
