### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by ghost** [meteor/mobile-packages#140]
Hi there,

are the packages *mdg:geolocation* and *mdg:camera* still being maintained?
Because the Cordova and plugin-versions are old and cannot run in Meteor 1.5.1 anymore?

Any help appreciated.

Regards

**Comment by Nauzer** [comment]
They run fine for me in 1.6.1

**Comment by lc3t35** [comment]
Why PR is not included in the package such as 
https://github.com/meteor/mobile-packages/pull/135

**Comment by StorytellerCZ** [comment]
A refresh is in progress.
