### ISSUE TITLE
mdg:camera using deprecated Chromium API

### ISSUE THREAD

**Issue by Nauzer** [meteor/mobile-packages#141]
Chrome gives me the following error message in console:

mdg_camera.js?hash=f907a9af3890137cfcbb7bb26d7ddfbcbc06889a:202 [Deprecation] URL.createObjectURL with media streams is deprecated and will be removed in M68, around July 2018. Please use HTMLMediaElement.srcObject instead. See https://www.chromestatus.com/features/5618491470118912 for more details.

Anyone working on this already or shall I prepare a Pull Request?

**Comment by abernix** [comment]
@Nauzer Nobody is working on this so if you're able to come up with a solution — we'd certainly be interested in reviewing a PR! (Though it's been ages since we've had to update this package, but if you can figure out a solution, we'll do our best!)

**Comment by Nauzer** [comment]
We will have a look at this - would be a shame if such often used package for Meteor would stop working ;-)

**Comment by abernix** [comment]
Thanks, @Nauzer!

**Comment by rafahoro** [comment]
@abernix I've just created a PR for this: https://github.com/meteor/mobile-packages/pull/144
Please let me know if there anything else I can do to help.
As mentioned in many places, this package is still an important one in the meteor community, so will be great if we can have it working again.

**Comment by filipenevola** [comment]
fixed on mdg:camera@1.4.2
