### ISSUE TITLE
Failed to execute 'createObjectURL' 

### ISSUE THREAD

**Issue by madc0w** [meteor/mobile-packages#143]
this code, which has worked reliably for a few years now:

> 			
> MeteorCamera.getPicture({
> 				quality : FULL_IMAGE_QUALITY,
> 				targetWidth : FULL_IMAGE_SIZE,
> 				targetHeight : FULL_IMAGE_SIZE
> 			}, function(err, data) {
> 				if (err) {
> 					// but why should canceling the camera be an error???
> 					if (err.error != "cancel") {
> 						clientUtils.logError("getPicture failed: " + err);
> 					}
> 				} else {
> 					callback(data);
> 				}
> 			});
> 

is now doing this instead:

			mdg_camera.js?hash=4bd2482b40124171625107361a13f27d78127c51:202 Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
			at success (mdg_camera.js?hash=4bd2482b40124171625107361a13f27d78127c51:202)

**Comment by rafahoro** [comment]
Hi. The reason is the same as in https://github.com/meteor/mobile-packages/issues/141  mdg:camera uses a now deprecated Chromium API

**Comment by filipenevola** [comment]
fixed on mdg:camera@1.4.2
