### ISSUE TITLE
mdg:camera incompatibility with latest meteor version

### ISSUE THREAD

**Issue by davinderkumar** [meteor/mobile-packages#152]
meteor add mdg:camera
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint less@1.0.0||2.0.0 is not satisfied by less 3.0.2.
Constraints on package "less":
* less@3.0.1 <- accounts-ui 1.4.0
* less@3.0.1 <- accounts-ui-unstyled 1.5.0 <- accounts-ui 1.4.0
* less@1.0.0||2.0.0 <- mdg:camera 1.5.2

**Comment by renanccastro** [comment]
Hi @davinderkumar. I've published mdg:camera@1.6.0 that upgrades mdg:camera to all latest packages!
