### ISSUE TITLE
Camera.destinationType to FILE_URI rather than DATA_URL

### ISSUE THREAD

**Issue by FrancoJ** [meteor/mobile-packages#20]
does the options params allow for navigator.camera.DestinationType.FILE_URI rather than the Data URI string?

As per Cordova's camera docs: 
To avoid common memory problems, set Camera.destinationType to FILE_URI rather than DATA_URL.

**Comment by jlynch80** [comment]
Yes, I too would find this useful.

**Comment by rwcatalano** [comment]
This would be really helpful.  Additionally a hook into aldeed's autoform would be a huge advancement.  Then you can embed the control in a form to collect additional metadata.

**Comment by jlynch80** [comment]
Agreed!

**Comment by gukii** [comment]
it would be useful and avoid memory problems.

**Comment by StorytellerCZ** [comment]
Closing due to age and in favor of #90
