### ISSUE TITLE
Picture Orientation

### ISSUE THREAD

**Issue by bdamato** [meteor/mobile-packages#21]
Photos don't seem to respect the camera orientation (vertical photos are being rotated to horizontal). I did some quick googling and it looks like this might explain it:

http://stackoverflow.com/questions/12700989/phonegap-return-current-orientation-during-image-capture

(add the "correctOrientation" : true option)

navigator.camera.getPicture(onPhotoDataSuccess, onFail, { quality: 50,
    destinationType: destinationType.FILE_URI, 
    correctOrientation: true });

**Comment by KristerV** [comment]
how about **we** add this to the readme? :)
