### ISSUE TITLE
Camera Selection

### ISSUE THREAD

**Issue by mkarliner** [meteor/mobile-packages#22]
There is currently no way to specify which camera to use.

**Comment by dtam** [comment]
+1

**Comment by dandv** [comment]
The front camera is always used on Android.

**Comment by cyounghusband** [comment]
That's annoying if you can't control which camera.  There are other cordova packages which seem to allow that, Meteor is just using the most basic and not maintaining it much.  I took a quick shot at adding a cordova package directly and failed.

**Comment by StorytellerCZ** [comment]
Closing this issue due to age.
