### ISSUE TITLE
Video and camera-popup height on mobile browser

### ISSUE THREAD

**Issue by luchux** [meteor/mobile-packages#25]
When rendering the camera-popup in mobile browser, the video element get a almost whole screen height, hiding the buttons for take picture and cancel. 

I am trying to fix it, but wondering if giving a fixed height to the video element is a bad idea. 

cheers

**Comment by programthis** [comment]
Did you resolve this? I'm having similar issues.

**Comment by StorytellerCZ** [comment]
Closing this issue due to age and since there have been a few commits in regards to the height of the popup.
