### ISSUE TITLE
App restarts after confirming photo from back camera on android

### ISSUE THREAD

**Issue by SylvainBigonneau** [meteor/mobile-packages#28]
You can try using the simple-photo example.

Run it on your Android phone, take a photo using the back camera, then press "OK" : the screen will go dark and the meteor splash screen will reappear, meaning the app just restarted.

I launched it using `meteor run android-device` : no error in the client or server console.

**Comment by pmp0x** [comment]
I have the same error. Did you find a fix?

**Comment by BraveKenny** [comment]
Sadly, no... It stopped happening a while ago, after I have had enough free space on my phone I think. But I'm pretty sure it would still happen if my phone didn't have enough memory again. t's definitely related to [that stackoverflow issue](http://stackoverflow.com/a/9524643/1439597) though

**Comment by KristerV** [comment]
in my case the very first test of the camera ended up restarting the app, but now it's fine.

**Comment by StorytellerCZ** [comment]
Closing this issue due to age.
