### ISSUE TITLE
Camera.PictureSourceType PHOTOLIBRARY or SAVEDPHOTOALBUM

### ISSUE THREAD

**Issue by pefi1011** [meteor/mobile-packages#29]
Can I somehow allow users to select an existing image from gallery?

**Comment by sasikanth513** [comment]
@pefi1011 Did you find any solution to select image from image gallery in android?

**Comment by pefi1011** [comment]
Unfortunately not

**Comment by sasikanth513** [comment]
@pefi1011 

```
  var cameraOptions = {
          targetWidth : 180,
          targetHeight : 180,
          allowEdit : true,
          destinationType : Camera.DestinationType.DATA_URI,
          sourceType:Camera.PictureSourceType.PHOTOLIBRARY
        };
        MeteorCamera.getPicture(cameraOptions, function (error, data) {
          if(!error){
            Meteor.call('updateUserImage',data)
          }
        });
```

I got this working

**Comment by StorytellerCZ** [comment]
Closing this issue due to its age and that we have found answer. @sasikanth513 it would nice if you could create a PR to the readme, docs or guide with some explanation about this. Thanks!
