### ISSUE TITLE
When using bootstrap 3, the photo display dialog is styled poorly

### ISSUE THREAD

**Issue by avital** [meteor/mobile-packages#30]
First of all, this is an amazing package!

When adding `mizzao:bootstrap-3`, the dialog showing a photo after it was taken has the image sticking out of it. The dialog for taking the photos is fine.

![screen shot 2014-12-22 at 7 19 56 pm](https://cloud.githubusercontent.com/assets/37586/5528322/8ad41d68-8a0f-11e4-805e-256c1d0b65c1.png)

**Comment by Tomrack** [comment]
Hello, once again great package you have made here, I was wondering if this has been fixed yet?

**Comment by StorytellerCZ** [comment]
Closing as this has been fixed.
