### ISSUE TITLE
Deprecated UI call in photo-browser.js 

### ISSUE THREAD

**Issue by babakness** [meteor/mobile-packages#31]
In photo-browser.js 

```
UI.insert(view, document.body);
```

> Warning: Blaze.insert has been deprecated.  Specify where to insert the rendered content in the call to Blaze.render.

**Comment by dandv** [comment]
Same error, from blaze.js:71.

**Comment by ridgemcghee** [comment]
I'm getting it, too (as of July 27, 2015).  I've run "meteor update".
