### ISSUE TITLE
Listen to "location ready" ?

### ISSUE THREAD

**Issue by hems** [meteor/mobile-packages#32]
Let's say i have a client side app with some javascript code which needs to know when the location is available.

Is there a simple "event" for that?

Sorry i'm still in this phase where everything is too magic and i can't figure out basics ( as in: i bet there is some general "meteor way" )

**Comment by stubailo** [comment]
If you call `Geolocation.currentLocation` or `Geolocation.latLng`, it will return null only if the location is not ready. So you can do something like:

```js
Template.map.helpers({
  location: function () {
    return Geolocation.latLng();
  }
});
```

```html
<template name="map">
  {{#if location}}
    Lat: {{location.lat}}, lng: {{location.lng}}
  {{else}}
    Location not ready
  {{/if}}
</template>
```

**Comment by hems** [comment]
but i need my JS to "listen" to it, so when it's ready i can call my functions?

**Comment by stubailo** [comment]
Try this:

```js
var callback = function () {....} // function to call when location is ready

Tracker.autorun(function (computation) {
  if (Geolocation.currentLocation()) {
    callback();
    computation.stop();
  }
});
```

Check out the docs for more details: <http://docs.meteor.com/#/basic/Tracker-autorun>

**Comment by hems** [comment]
cool! i was doing that, but did not have the "computation" trick! thanks for that!
