### ISSUE TITLE
Camera Modal Conflict With Ionic Modal

### ISSUE THREAD

**Issue by panw** [meteor/mobile-packages#34]
I am using this package with Ionic. I have a camera button inside an Ionic Modal. When I activate the camera it seems to be behind the Ionic Modal (only when I dismiss the modal I could interact with the camera controls) However, looking at the CSS the camera-popup has the highest z-index.

```
.camera-popup {
position: fixed;
z-index: 1000;
top: 20%;
width: 320px;
left: 50%;
margin-left: -150px;
font-family: sans-serif;
background: white;
box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
line-height: 1.3em;
padding: 20px;
border-radius: 10px;
}
```

```
.modal-backdrop {
  -webkit-transition: background-color 300ms ease-in-out;
  -moz-transition: background-color 300ms ease-in-out;
  transition: background-color 300ms ease-in-out;
  position: fixed;
  top: 0;
  left: 0;
  z-index: 10;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0);
}
```

**Comment by panthongw** [comment]
Looked into this some more and the problem is due to the fact that the Ionic modal specifies ``pointer-events: auto``, so if the camera package is specified with ``pointer-events:auto`` as well then the camera modal button would be clickable.

**Comment by nickw** [comment]
@panthongw I'm working on an Ionic-specific version of the camera plugin, I'd love your feedback: https://github.com/meteoric/camera

**Comment by stubailo** [comment]
Very nice! That's a great idea for a package. Let me know if there are fixes/improvements I can backport here, unfortunately I don't have too much time to work on this package.

@nickw is the goal of the ionic version to work on desktop as well, or only mobile?

**Comment by nickw** [comment]
Thanks @stubailo - I tried to do some refactoring but ended up making a mess haha. I may try to rewrite it from scratch if I get time.

Re: desktop, I'm going to stick with Ionic's direction for now which is mobile-only.

**Comment by panthongw** [comment]
@nickw thanks for letting me know about you package. I'll definitely check it out and let you know any feedback I have.
