### ISSUE TITLE
Why geolocation always running ?

### ISSUE THREAD

**Issue by berkaey** [meteor/mobile-packages#35]
```
    # get location data
    Tracker.autorun (computation) ->
        if Geolocation.currentLocation()
            Meteor.call "getNearCities",Geolocation.latLng(),(e,data)->
                Session.set("nearLocations",data)
            computation.stop()
```

hi I use this code to get location but I need only one time per reload but this seems working always how can I stop this?

**Comment by stubailo** [comment]
Can you post a complete app that demonstrates the issue?

**Comment by berkaey** [comment]
ok http://showtimes.meteor.com but I don't know but not working good on deploy and also noticed that I was asked 3 times to give permission to location data

**Comment by MichaelFBA** [comment]
I'm also finding extremely high battery usage due to GPS.

**Comment by lukasvan3l** [comment]
+1 this is a battery drain in my app :( Would like to get a fix once, and then stop the GPS being used. Has anyone built this yet?

**Comment by stubailo** [comment]
You can use the native geolocation API if you don't want a reactive source, like in the Mozilla docs above.

**Comment by lukasvan3l** [comment]
indeed I ended up using this: 
var currentLatLng = new ReactiveVar(null);
var checking = false;
this.GetLatLng = function() {
  if (currentLatLng.get() == null && !checking) {
    checking = true;
    navigator.geolocation.getCurrentPosition(function(position) {
      check(position.coords.latitude, Number);
      check(position.coords.longitude, Number);
      console.log('Found you at', position.coords);
      currentLatLng.set(position);
      checking = false;
    }, function(error) {
      console.error(error);
    });
  }
  return currentLatLng.get();
}

**Comment by StorytellerCZ** [comment]
Closing this issue due to age.
