### ISSUE TITLE
[Camera] Use a background thread 

### ISSUE THREAD

**Issue by lorensr** [meteor/mobile-packages#37]
I get this warning when calling `getPicture` on ios-device: 

`THREAD WARNING: ['Camera'] took '1005.238281' ms. Plugin should use a background thread.`

**Comment by stubailo** [comment]
Interesting - this seems like a problem with the Cordova plugin itself, rather than the JavaScript code in this package.

**Comment by lorensr** [comment]
Thanks, well I would repost the issue there, but they don't take issues :)

https://github.com/apache/cordova-plugin-camera

**Comment by stubailo** [comment]
Alright, sorry I can't help with this! Does it cause any undesirable behavior, or is it just the warning?

**Comment by Slava** [comment]
@lorensr you should report it on their JIRA: https://issues.apache.org/jira/browse/CB

**Comment by lorensr** [comment]
@stubailo Probably not, suppose could be related to #38 

@Slava thanks, done:

https://issues.apache.org/jira/browse/CB-8340
