### ISSUE TITLE
[Camera] Second call to getPicture doesn't work

### ISSUE THREAD

**Issue by lorensr** [meteor/mobile-packages#38]
To reproduce on `ios-device`:
- call `getPicture`
- take a picture
- select "Use Photo"
- call `getPicture` again

You get this screen, with a black image:

![2015-01-18 18 48 14](https://cloud.githubusercontent.com/assets/251288/5795372/7acbd700-9f43-11e4-9fa7-42af17ea6723.png)

Tapping the "take" button does nothing, tapping the "change camera" button appears to show a blurry version of the last picture taken.

You can successfully take a picture again if you restart the app.

**Comment by StorytellerCZ** [comment]
Closing this issue due to age.
