### ISSUE TITLE
Question: Camera.getPicture: source type 1 not available.

### ISSUE THREAD

**Issue by cramhead** [meteor/mobile-packages#4]
I've been trying to get the camera to work with the simple-photo example. 
I consistently get this message. Even after updating to rc8 and changing the camera dependency from 3.0 to 3.1. 
When I change sourceType to Camera.PictureSourceType.PHOTOLIBRARY it does ask for permission to the photo library and if I allow it shows what's there.

Any thoughts?

**Comment by rwitchell** [comment]
Can you recommend how to check?
i'm doing this:

if( ionic.Platform.isIOS() || ionic.Platform.isAndroid() || ionic.Platform.isWindowsPhone() ) {
          CameraFactory.getPicture();
}

which works on a device.
but i would also like to add
 else if( /* device is iphone simulator */ ) {
  // use Camera.PictureSourceType.PHOTOLIBRARY
} else if ( /* device is computer / testing / dev */ ) {
  // use upload image dialog box.
}

**Comment by stubailo** [comment]
Yeah it's hard to detect if you are running in a simulator or on an actual device with Cordova. It's also hard to reliably tell the difference between a desktop and mobile browser without relying on screen width. I think your best bet would be to try to get a picture from the camera then use photo library if it fails, and use feature detection to see if you can get a video stream from the browser and use a photo upload box if not.
