### ISSUE TITLE
[geolocation] latLng only works after calling currentLocation

### ISSUE THREAD

**Issue by lorensr** [meteor/mobile-packages#43]
I give the tab access to my location, and I then do the following in the console:
```js
> Geolocation.latLng()
null
> Geolocation.currentLocation()
Geoposition {timestamp: 1422413895716, coords: Coordinates}
> Geolocation.latLng()
Object {lat: 37.0..., lng: -122.0...}
```

**Comment by stubailo** [comment]
Are you sure there isn't a delay for the location becoming available? Geolocation.latLng actually calls Geolocation.currentLocation.

**Comment by lorensr** [comment]
Haha, thanks. I tested it a few times to be sure before posting, but I was always not waiting long enough :)

**Comment by minafarid** [comment]
Is there a way to synchronously wait until location is available? Or is there a callback when the location becomes available?

**Comment by lorensr** [comment]
Not provided by this package's API, but it is using a cb:

https://github.com/meteor/mobile-packages/blob/master/packages/mdg:geolocation/geolocation.js#L28
