### ISSUE TITLE
Camera on android emulator needs sd card

### ISSUE THREAD

**Issue by mininao** [meteor/mobile-packages#44]
Hello everybody,

After adding the camera package and testing it out in the android emulator, i get the following error :  
![selection_419](https://cloud.githubusercontent.com/assets/5511564/5937374/161a6516-a6ef-11e4-9d62-cea53323949b.png)

Any idea how to tweak the emulator to support sdcards ?

**Comment by davidxiao** [comment]
same issue

**Comment by dtam** [comment]
+1

**Comment by jay61439476** [comment]
+1

**Comment by thomasf1** [comment]
+1

**Comment by stubailo** [comment]
you can fix this temporarily by running `meteor configure-android avd`, and then adding an SD card to the virtual device.

**Comment by jay61439476** [comment]
It works~  thanks

**Comment by mininao** [comment]
Thanks !
