### ISSUE TITLE
EXIF information from camera

### ISSUE THREAD

**Issue by klopfer** [meteor/mobile-packages#46]
Is there a way to get EXIF metadata from the camera?  

It seems to only report width and height, but not other standard metadata like date or lat/lon.  I think the cordova camera can do this normally (outside of meteor).

**Comment by dandv** [comment]
For browsers, http://www.w3.org/TR/image-capture/#photocapabilities maybe?

**Comment by klopfer** [comment]
Thanks.  I've figured out how to get EXIF data out if it is there.  But it doesn't actually seem to be saved to the file when using the camera using this package (at least on iOS).

**Comment by dandv** [comment]
@klopfer: how did you get the EXIF data? Did that API work? I'd like to work on this package a bit in the future; maybe I can stuff the data into the image.

**Comment by klopfer** [comment]
You can get it on the client side from this library.  https://github.com/jseidelin/exif-js.  There are also ways of getting it on the server side from https://github.com/CollectionFS/Meteor-CollectionFS.  But of course the data needs to be there.  So an upload on a web browser works just fine.  But the camera module doesn't include that info.
