### ISSUE TITLE
[Android] Turning GPS on while app is running does not work?

### ISSUE THREAD

**Issue by SylvainBigonneau** [meteor/mobile-packages#54]
I do no know if it is in the scope of this project, but when I start up, say, simple-map on my Android phone with the GPS turned off, and only then turn the GPS on while the app is running, meteor is unable to catch that activation. (also, the geolocation icon does not appear in the status bar, unless I am using another geolocation app in the background)

Only if I press the back button does it "reload" the app and then it works, and the geolocation icon appears. It also works if I have GPS turned on prior to launching the app.

Is there a way to detect GPS activation within the meteor app? Or should I put a "check again" button on my app that does  ̀window.location.reload()` ?

**Comment by caio-ribeiro-pereira** [comment]
Hi, I helped solve this issue, sending this PR (https://github.com/meteor/mobile-packages/commit/df1b1743bbffd8112e866fca16dc4b675d95e94a).
Please, update this package for version 1.0.3, and to solve your problem, you just need to run this code below to check if the GPS is turned on:

``` javascript
Template.gps.helpers({
    hasGPS: function() {
        return !!Geolocation.error();
    }
});
```

and in your template use this snippet:

``` html
<template name="gps">
    {{#if hasGPS}}
         <h1>GPS online!</h1>
    {{else}}
        <h1>GPS offline, turn the gps on and <a href="#" onclick="window.location.reload();">reload the app</a>.</h1>
    {{/if}}
</template>
```

This code runs on mobile too. I hope this code can help you!

**Comment by BraveKenny** [comment]
Thanks a lot! That solves the detection problem! Now we only need to find a way to *not* ask the user for a manual reload, as any production app would not.

**Comment by caio-ribeiro-pereira** [comment]
I didn't find a way to create a button for turn on gps, but if you find
please share with us!

Att,
Caio Ribeiro Pereira
Software Engineer
http://crpwebdev.com

**Comment by vinaypuppal** [comment]
Hope this might be helpful to who reach here with this GPS  problem. Plugin for phonegap/cordova to display a dialog and redirect to GPS settings when the GPS is disable. https://github.com/rodrigo-martinezd/cordova-dialog-gps

**Comment by dhavalrajani92** [comment]
Hello @vinaypuppal have you used with meteor?

**Comment by vinaypuppal** [comment]
@dhavalrajani92  Yes I have used it working perfectly, here is the tarball url https://github.com/rodrigo-martinezd/cordova-dialog-gps.git#f1103143fcf725fb98be8af7cbf98383945225ab

**Comment by StorytellerCZ** [comment]
I'm closing this issue as it has been fixed.
