### ISSUE TITLE
"more than one device and emulator" on Linux + Android

### ISSUE THREAD

**Issue by dandv** [meteor/mobile-packages#55]
If I happen to have my Android connected to my Ubuntu when I run `meteor run android`, meteor will display

> error: more than one device and emulator
> - waiting for device -

It's easy enough to disconnect the phone, but is there a better way to handle this situation?

The same error occurs with `meteor run android-device` if the emulator is still running.

**Comment by macroramesh6** [comment]
I have a same problem when I test my app in multiple device

**Comment by roelvan** [comment]
same problem here

**Comment by dnuske** [comment]
but you have the same issue if you are not using this plugin, I don't think this goes here that is more a Meteor thing.

**Comment by macroramesh6** [comment]
I found simple hack to run app in multiple devices. 

1. Execute `meteor run android-devices --verbose` without connect android device. 

 Command end with:
`ERROR: Failed to launch application on device: ERROR: Failed to install apk to device: ERROR: Failed to deploy to device, no devices found.
Command finished with error code 8: sampleapp/.meteor/local/cordova-build/platforms/android/cordova/run --device`

    `ERROR running one or more of the platforms:
Error: sampleapp/.meteor/local/cordova-build/platforms/android/cordova/run: Command failed with exit code 8
You may not have the required environment or OS to run this project`

2. Now connect single device and execute the command in new terminal that come up with the above lines eg: `sampleapp/.meteor/local/cordova-build/platforms/android/cordova/run --device`

3. Then remove current device and connect new device. repeat the same to all your test device.

4. Connect all your device into you machine and start develop

I dont know whether its good, but works :+1:

**Comment by lorensr** [comment]
For step 2. to work, I had to `export ANDROID_HOME=/Users/me/.meteor/android_bundle/android-sdk/` and add `/Users/me/.meteor/android_bundle/apache-ant-1.9.4/bin` to `PATH`

**Comment by uriva** [comment]
+1 for support for debugging on multiple devices

**Comment by StorytellerCZ** [comment]
I'm closing this issue as this should be a feature request on the [main Meteor repository](https://www.github.com/meteor/meteor).
