### ISSUE TITLE
Android app always offline, even if the phone is online

### ISSUE THREAD

**Issue by joaopiopedreira** [meteor/mobile-packages#59]
Hi, have an Android app with appcache + reload-on-resume. 

I build the app and install the apk in an Android device. 

When the app first starts, everything is ok. 

Then I force the offline mode on the phone (WI-FI off). I get the info that the app is offline (msg based on Meteor.status()). 

When I turn WI-FI on again, the app never recovers from offline mode. 

This doesn't happen if I have just appcache (without reload-on-resume) installed.

What am I doing wrong? 

Thanks

**Comment by balaianu** [comment]
+1 I have the same problem. Any solution?

**Comment by StorytellerCZ** [comment]
Closing this issue due to age. Will look into reload-on-resume soon.
