### ISSUE TITLE
Geolocation.latLng() gets updated only when the browser is refreshed or tab is re focused 

### ISSUE THREAD

**Issue by prathviraj080** [meteor/mobile-packages#61]
As mentioned in the documentation, 
"Every method is reactive using Tracker"
I'm not able to see the reactive update of Geolocation.latLng() values. I can see updated values only when I reload the page or re focus on the tab where the app is running.

**Comment by stubailo** [comment]
Where are you calling the function? If you are not calling it inside of a helper or autorun, it won't be reactive.
