### ISSUE TITLE
mdg:location ~ Geolocation.currentLocation() returns null even when location is available through browser navigator.geolocation.getCurrentPosition

### ISSUE THREAD

**Issue by hems** [meteor/mobile-packages#63]
The first time i install my app the application is getting an onError "TIMEOUT" and don't try to fetch the position anymore.

The side effect is that `Geolocation.currentLocation()` will be null even after the user has authorized the location service, therefore making the location available through: `navigator.geolocation.getCurrentPosition( my_callback )`

related to: https://github.com/meteor/mobile-packages/issues/62

**Comment by skhan02** [comment]
You have to call the the currentLocation() inside of a helper or autorun. Check the solomo example on the github page!

**Comment by sunlee-newyork** [comment]
@skhan02 worked for me, thank you!

**Comment by rashmimhatre100** [comment]
Working with meteor react getting the same problem i.e null. 

`

  handleMapOptions() {
    Tracker.autorun(() => {
    var latLng = Geolocation.currentLocation();
    var latLng1 = Geolocation.latLng();
    // Initialize the map once we have the latLng.
    console.log(latLng);      
    console.log(latLng1);      
    });


    if (GoogleMaps.loaded()) {
      return {
        center : new google.maps.LatLng(37.779161, -122.435228),
        zoom   : 12,
      };
    }
  }
`

**Comment by StorytellerCZ** [comment]
For React you should use the `useTracker` hook or `withTracker` HOC.
