### ISSUE TITLE
FR: Allow customizable name for iOS permission dialog

### ISSUE THREAD

**Issue by lorensr** [meteor/mobile-packages#68]
I'd rather it say my app's name instead of `http://meteor.local`:

![2015-06-27 20 24 35](https://cloud.githubusercontent.com/assets/251288/8394709/5aeb09b6-1d14-11e5-9388-f7e451d57126.png)

**Comment by KFoxder** [comment]
+1

**Comment by skirunman** [comment]
@lorensr I know this is very, very old, but I think this should just work in Meteor 1.6  if you add your app name to your `mobile-config.js`.

```
App.info({
  id: 'com.myapp.myapp',
  name: 'Myapp',
  version: '0.1.0',
  description: 'My cool app',
  author: 'My company',
  email: 'support@mycompany.com',
  website: 'https://mycompany.comi'
});
```

I'd like to know if you have a problem with this as I'm planning to update Meteor Guide mobile section with additional information on configuring your iOS app.

**Comment by lorensr** [comment]
Thanks, that would be nice! Can't confirm in my app, not working on it any longer
