### ISSUE TITLE
what is the permission needs to be given to the app to open camera for a video chat

### ISSUE THREAD

**Issue by hemant4bluepi** [meteor/mobile-packages#69]

**Comment by hemant4bluepi** [comment]
OT.Publisher.onStreamAvailableError Permission Denied .......

**Comment by kamaldlk** [comment]
OT.Publisher.onStreamAvailableError Permission Denied me too getting this erro :( 

boss ru completed this

**Comment by StorytellerCZ** [comment]
I'm closing this issue due to its age.
