### ISSUE TITLE
Camera doesn't seem to work in iOS8

### ISSUE THREAD

**Issue by zackify** [meteor/mobile-packages#7]
I know I correctly implemented the camera package because viewing my meteor app in the browser works correctly and returns a photo, the iOS app on my 6 Plus in iOS 8 will let me take a photo but nothing gets returned while doing: 

```
if (Meteor.isClient) {
  // counter starts at 0
  Session.setDefault("counter", 0);

  Template.hello.helpers({
    counter: function () {
      return Session.get("counter");
    },
    picture: function(){
      return Session.get("picture");
    }
  });

  Template.hello.events({
    'click button': function () {
      // increment the counter when button is clicked
      MeteorCamera.getPicture(function(err,res){
        if(!err) Session.set("picture", res);
      })
    }
  });
}
```

Console in Xcode and meteor show nothing wrong after selecting the photo though

**Comment by KristerV** [comment]
would like a status update on this. Haven't got a iPhone myself, but want to use this package.

**Comment by StorytellerCZ** [comment]
I'm closing this since the Cordova plugin has been updated.
