### ISSUE TITLE
No Documentation for 'sourceType' Option

### ISSUE THREAD

**Issue by tomglenn** [meteor/mobile-packages#70]
Late last night I was ready to ditch the mdg:camera package because what I really needed was the ability to allow a user to select a photo from their mobile device's photo library to upload an Avatar, but all I could achieve was a "Take Photo" popup which didn't match my apps styling and didn't give me the results I wanted.

But after a little more searching it would appear that the mdg:camera package does actually support choosing a photo from the user's library. I haven't test this yet, but a lot of places suggesting the 'sourceType' attribute and setting it to 'Camera.PictureSourceType.PHOTOLIBRARY'.

Why is this not in the mdg:camera documentation?
There also doesn't appear to be any documentation with regards to overriding the popup interface.

**Comment by VioletaCalvo** [comment]
It would be great if user could choose if he wants to take a new photo or to select a photo from his photo library.
I would like sourceType also appears in mdg:camera documentation :+1:

**Comment by VioletaCalvo** [comment]
@tomeglenn mdg:camera options are Phonegap camera options, so we can found souceType options in Phonegap documentation:
http://docs.phonegap.com/en/edge/cordova_camera_camera.md.html
(camera.getPicture section)
