### ISSUE TITLE
mdg:geolocation SesionSet.get('geoLocation') returns empty object

### ISSUE THREAD

**Issue by aleksandrenko** [meteor/mobile-packages#71]
if(Meteor.isClient) {

  Tracker.autorun(function() {
    var g = Geolocation.currentLocation();
    if(g) {
      console.log('set', g);
      Session.set('g',g);
      console.log('get', Session.get('g'));
   }
  });

The console outputs are as follow:
set Geoposition {}
get Object {}

Setting the geolocation object in a Session does not work.
Can someone take a look :)

**Comment by skhan02** [comment]
You have to call the the currentLocation() inside of a helper or autorun. Check the solomo example on the github page!
