### ISSUE TITLE
mdg:reload-on-resume not working on iOS

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/mobile-packages#72]
I tried this package to solve my hot push problems (which will sometimes break my app completely). But it doesn't work. Even if I add mdg:reload-on-resume to my project, hot pushes are requested from my iOS app. So I'm wondering if this package is broken somehow?

BTW: I've also noticed that the app now runs a hot code push every time I start it, even if the server code hasn't been changed in the meantime. So, at least to my experience, this package is exactly doing the oppositie of what I would have expected. Instead of delaying the hot code push, it triggers it more often (on each app reload). And what makes this even worse: During this very first hot reload, the app already reacts to user input (e.g. the launch screen disappears). Which is a problem since the problems I tried to resolve were related to user interactions during hot reload, so my problems now are even more likely to happen. [EDIT: This second problem disappeared after doing a meteor reset and re-installing the app from scratch. Yet, the main problem still exists: the package just does not do what it is intended to do, i.e. it does not have any effect on the hot push mechanism.]

**Comment by StorytellerCZ** [comment]
Please see the new guide on hot code push: https://guide.meteor.com/hot-code-push.html
