### ISSUE TITLE
save photo automatic to directory 

### ISSUE THREAD

**Issue by YouSour** [meteor/mobile-packages#74]
hi , how can i save photo automatic to directory (Example : D:/picture) when i click on button take photo ? 
thank you for advance :)

**Comment by StorytellerCZ** [comment]
You can't do that as that would violate security as the browser does not have access to the filesystem in that way. User will always need to select destination or it will be downloaded to the destination that the user set in the browser's settings.

**Comment by YouSour** [comment]
lol , just got a reply , thank anyway
