### ISSUE TITLE
mdg:camera MeteorCamera.takePicture() not calling callback

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/mobile-packages#77]
I'm using this code inside a template event handler:

``` js
console.log('calling getPicture()');
MeteorCamera.getPicture(function(error, base64DataURI) {
  console.log('inside callback');
});
```

On my device (iPad3, iOS8, app compiled with Xcode7), the first console.log() is executed and the camera is activated. But after taking a picture and tapping on "Use photo", the callback is not called.

Instead, I'm seeing this message in Xcode's log window:

```
Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
```

I've also noticed that if I embed the Meteor web view in a custom container view, this container view is replaced by a full-screen web view after the camera returns. But this is just a side-effect, the problem mentioned above also happens in a plain-vanilla Meteor Cordova app, without any changes to the standard view controller.

EDIT: On Android, this is working fine. The problem only occurs on iOS.

**Comment by StorytellerCZ** [comment]
I'm closing this issue due to its age.
