### ISSUE TITLE
why are packages not in own repos?

### ISSUE THREAD

**Issue by adamwong246** [meteor/mobile-packages#78]
This is less of an issue, more of a gripe... but why are these 3 packages living in the same repo?

I'd like to fork the camera package whilst maintaining git history but with this configuration, I don't see how it's possible.

**Comment by stubailo** [comment]
You can still fork the repo, and just not modify the other two packages.

It's annoying to have too many git repos - if Meteor was split into 250 repositories, one for each package, I don't think that would be good for anyone.
