### ISSUE TITLE
Camera modal auto-takes picture on Android 5.0

### ISSUE THREAD

**Issue by programthis** [meteor/mobile-packages#79]
Instead of showing a video in the modal to allow the user to select the position of the picture, the camera seems to autosnap it. I'm trying to test this in the Chrome browser on a Nexus 5 running Android 5.0.

This is an extension of a question that [was asked here](https://github.com/Urigo/angular-meteor/issues/544).

**Comment by StorytellerCZ** [comment]
I'm closing this issue due to its age.
