### ISSUE TITLE
Not load Google Maps

### ISSUE THREAD

**Issue by diegocandido** [meteor/mobile-packages#82]
Debbug does not load the Google Maps ?  The android, but in chrome work.

**Comment by tehuglyduckilg** [comment]
I ran into this when I ran `meteor update` on my project.  From https://github.com/dburles/meteor-google-maps there is a bit about working on mobile devices. I added a file called `mobile-config.js` to my project with the text:

```
App.accessRule('*.google.com/*');
App.accessRule('*.googleapis.com/*');
App.accessRule('*.gstatic.com/*');
```

and the map is working on my mobile device again. Hope this helps.

**Comment by elalemanyo** [comment]
I add the accessRule to my mobile-config.js and I get a timeout. Can anyone help me with this?

Thanks

**Comment by StorytellerCZ** [comment]
I'm closing this issue due to its age.
