### ISSUE TITLE
Android Device Pictures Not Oriented Correctly

### ISSUE THREAD

**Issue by ghost** [meteor/mobile-packages#83]
I was having an issue where my images were not being saved with the correct orientation.  After reading the issue here https://github.com/meteor/mobile-packages/issues/21 I edited the devshop-demo.js `Template.layout.events` to:

```
  Template.layout.events({
    "click .photo-link": function () {
        var cameraOptions = {
            correctOrientation: true
      };
      MeteorCamera.getPicture(cameraOptions,function (error, data) {
        // we have a picture
        if (! error) {
          onSuccess(data);
        }
      });
    }
  });
```

This seems to be working so far for me.

**Comment by StorytellerCZ** [comment]
See #21
