### ISSUE TITLE
[bug?] Camera view on Android Chrome partially off-screen.

### ISSUE THREAD

**Issue by trusktr** [meteor/mobile-packages#85]
![screenshot_2015-09-17-18-11-20_1024](https://cloud.githubusercontent.com/assets/297678/9952039/a2a388c2-5d84-11e5-9db7-64f1626862aa.png)

That's on my Nexus 5. My front camera is broken. x}

**Comment by trusktr** [comment]
I'll probably debug this at some point, but I'm more focused on cordova right now.

**Comment by StorytellerCZ** [comment]
Closing this issue due to age. There have also been changes to scaling so it should be fixed now as well.
