### ISSUE TITLE
Upgrading to Meteor 1.2 is not possible with current camera package constraints 

### ISSUE THREAD

**Issue by sferoze** [meteor/mobile-packages#86]
I am trying to upgrade and I get this error

```
Update to release METEOR@1.2.0.1 is impossible:
While selecting package versions:             
error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0_2.
Constraints on package "less":
* less@=2.5.0_2 <- top level
* less@1.0.11 <- multiply:iron-router-progress 1.0.1
* less@1.0.0||2.0.0 <- mdg:camera 1.1.5
```

I am being held back partly by mdg:camera 

Do you have to update the package or am I doing something wrong?

**Comment by stubailo** [comment]
I think you are being held back entirely by `multiply:iron-router-progress`.

**Comment by sferoze** [comment]
why does it specify the camera?

**Comment by stubailo** [comment]
It is listing _all_ packages that depend on LESS, because there are two possible solutions: either remove everything that depends on version 2, or everything that depends on version 1.

**Comment by sferoze** [comment]
so for mdg camera it says `less@1.0.0||2.0.0 <- mdg:camera 1.1.5`

does that mean the camera will work with 1.0 and 2.0?

**Comment by stubailo** [comment]
Yep, exactly right.
