### ISSUE TITLE
Cordova: Add permissions

### ISSUE THREAD

**Issue by dnish** [meteor/mobile-packages#88]
Hey,
is there any way to add permissions to my Cordova project via mobile-config.js? I just change settings via <code>App.setPreference();</code> but don't know if we can set also permissions here, f.e.:

```
<uses-permission android:name="android.permission.CAMERA" />
```

**Comment by inspiraluna** [comment]
any news on that? its really needed for me too…

**Comment by Pushplaybang** [comment]
any update here?  need to add access to the microphone?

**Comment by ramezrafla** [comment]
You can use an empty plugin to add permissions, see here https://forums.meteor.com/t/meteor-cordova-add-permissions/10625

**Comment by Pushplaybang** [comment]
You'll also need to use the diagnostic plugin for runtime permissions.

https://github.com/dpa99c/cordova-diagnostic-plugin
