### ISSUE TITLE
Browser camera asks for permission on every picture

### ISSUE THREAD

**Issue by arbesfeld** [meteor/mobile-packages#9]
MeteorCamera.getPicture() requires that the user give browser camera access on every photo.

**Comment by mariorodriguespt** [comment]
+1

I also noticed that my web cam remains active, on Google Chrome, after the modal is dismissed, which is scary for any normal user.

**Comment by mininao** [comment]
:+1: Bug exists on FF 35.0

**Comment by dandv** [comment]
Would be great if permission were requested only once.

**Comment by guilhermedecampo** [comment]
Seems that this ends if you are over SSL. 

>If your app is running from SSL (https://), this permission will be persistent. That is, users won't have to grant/deny access every time.

found this from here: http://www.html5rocks.com/en/tutorials/getusermedia/intro/

**Comment by StorytellerCZ** [comment]
I was not able reproduce recently, so I'm closing the issue.
