### ISSUE TITLE
iOS-device: undefined is not an object (evaluating 'navigator.camera.getPicture')

### ISSUE THREAD

**Issue by Streemo** [meteor/mobile-packages#93]
Using the mdg:camera package. Call to MeteorCamera.getPicture works perfectly on Android device. However, on iOS device, it throws the above error. Any ideas as to why this is happening?

The code is being called in a 'click' Template event. **We tried wrapping the call in a Meteor.startup, but this did not work.**

Has anyone else encountered this problem? 

Thanks; help much appreciated.

Edit: 

In the Safari web inspector for my iPhone (physical device), navigator.camera === undefined (including in Meteor.startup code). In Android, it is defined, and works as expected.

**Comment by lucfranken** [comment]
Related forum topic https://forums.meteor.com/t/piece-of-code-in-mdg-camera-works-in-cordova-android-but-not-ios/12745

**Comment by StorytellerCZ** [comment]
Closing this issue due to age.
