### ISSUE TITLE
Getting a "deprecated" message in Chrome. GMaps is not loading.

### ISSUE THREAD

**Issue by mondrus** [meteor/mobile-packages#96]

**Comment by sasikanth513** [comment]
may be related to #97 the issue might be because of new security updates from chrome?

**Comment by sasikanth513** [comment]
@mondrus Did you find any solution for this?

**Comment by StorytellerCZ** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while and are missing any details to really pursue this.
