### ISSUE TITLE
mdg:camera gives "Uncaught TypeError: stream.stop is not a function"

### ISSUE THREAD

**Issue by bartuelen** [meteor/mobile-packages#98]
MediaStream.stop() has been deprecated in Chrome.

In the mdg:camera package this results in the console.log error message "Uncaught TypeError: stream.stop is not a function" when running the application.

See https://developers.google.com/web/updates/2015/07/mediastream-deprecations
See also https://github.com/andyet/SimpleWebRTC/issues/363

**Comment by perak** [comment]
:+1:

**Comment by perak** [comment]
@bartuelen I modified this package and published as: https://github.com/perak/meteor-camera/

That's temporary solution, I don't think I'll maintain this package in the future...

**Comment by Rebolon** [comment]
:+1:

**Comment by codeHatcher** [comment]
+1

**Comment by bartuelen** [comment]
I close this issue. Solution is clear.
