### ISSUE TITLE
GeoLocation is not working anymore in mobile apps 

### ISSUE THREAD

**Issue by sasikanth513** [meteor/mobile-packages#99]
GeoLocation API is not working in mobile apps

I have two apps with following versions

**1st app**

meteor version - 1.2.0.2 (latest)
mdg:geolocation - 1.1.0 (latest)

**2nd app**

meteor version - 1.1.0.2 
mdg:geolocation - 1.0.3

In both apps I'm getting same warning
<img src="https://discourse-cdn.global.ssl.fastly.net/meteor/uploads/default/original/2X/3/344ced27fb1a3d1c2041bdeae861efa8da87bef3.png" width="690" height="300">

I've tried to create apks for both apps and tried with the apks, still they are not working.

Any suggestions or help here

**Comment by derouck** [comment]
You will need to use a secured connection for your application. The yellow message on top of your page indicates this. It will probably be broken in chrome as well. I think Firefox currently still allows it.
